/** Controlled templates assembled from Safety Blocks — add a form here, not a new page. */
import { assembleForm } from "../assemble";
import {
  CRANE_INSPECT_ITEMS,
  MONTHLY_MAINT_ITEMS,
  RIGGING_INSPECT_ITEMS,
  SITE_INSPECT_ITEMS,
  WEEKLY_MAINT_ITEMS,
} from "../blocks";
import type { WhoopFormDef } from "../types";

export const FORM_TEMPLATES: WhoopFormDef[] = [
  assembleForm({
    id: "flha",
    title: "FIELD LEVEL HAZARD ASSESSMENT",
    number: "WHOOP-FRM-001",
    group: "Daily",
    description:
      "This shift, this lift, this ground. Not a signature collection.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "crane" },
      { type: "hazard" },
      { type: "hazard" },
      { type: "control" },
      { type: "control" },
      { type: "ppe" },
      { type: "communication" },
      { type: "weather" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "crane-pre-use",
    title: "CRANE PRE-USE INSPECTION",
    number: "WHOOP-FRM-002",
    group: "Daily",
    description: "This shift, this machine, this configuration. 14.35.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: CRANE_INSPECT_ITEMS },
      { type: "weather" },
      { type: "powerlines" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "rigging-inspection",
    title: "RIGGING INSPECTION",
    number: "WHOOP-FRM-003",
    group: "Daily",
    description: "Before the hitch takes load. Part 15.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "rigging" },
      { type: "inspection", inspectionItems: RIGGING_INSPECT_ITEMS },
      { type: "comments" },
      { type: "photo" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "crane-op-log",
    title: "CRANE OPERATOR LOG",
    number: "WHOOP-FRM-023",
    group: "Logs",
    description:
      "Hours, lifts, defects — dated and signed. Stays with the machine. 14.14.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: CRANE_INSPECT_ITEMS },
      { type: "log" },
      { type: "weather" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "rigger-log",
    title: "RIGGER LOG",
    number: "WHOOP-FRM-024",
    group: "Logs",
    description:
      "Gear used, lifts made, what was isolated. 15.31 before each shift.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "load" },
      { type: "rigging" },
      { type: "inspection", inspectionItems: RIGGING_INSPECT_ITEMS },
      { type: "log" },
      { type: "photo" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "jha",
    title: "JOB HAZARD ANALYSIS",
    number: "WHOOP-FRM-JHA",
    group: "Lifting",
    description:
      "Hazards, consequence, residual risk. The steps live in the SWP.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "hazard" },
      { type: "hazard" },
      { type: "hazard" },
      { type: "control" },
      { type: "control" },
      { type: "control" },
      { type: "ppe" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "lift-plan",
    title: "LIFT PLAN",
    number: "WHOOP-FRM-006",
    group: "Lifting",
    description: "Weight, COG, chart, path, people, abort — before the hook.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "crane" },
      { type: "load" },
      { type: "rigging" },
      { type: "communication" },
      { type: "weather" },
      { type: "powerlines" },
      { type: "emergency" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "critical-lift",
    title: "CRITICAL LIFT PLAN",
    number: "WHOOP-FRM-007",
    group: "Lifting",
    description: "Named supervision. Written plan. 14.42.1.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "crane" },
      { type: "load" },
      { type: "rigging" },
      { type: "hazard" },
      { type: "hazard" },
      { type: "control" },
      { type: "control" },
      { type: "communication" },
      { type: "weather" },
      { type: "powerlines" },
      { type: "emergency" },
      { type: "comments" },
      { type: "signature" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "pre-lift-meeting",
    title: "PRE-LIFT MEETING",
    number: "WHOOP-FRM-009",
    group: "Lifting",
    description: "Everyone repeats the plan, the signals, who stops it.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "load" },
      { type: "hazard" },
      { type: "control" },
      { type: "communication" },
      { type: "ppe" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "site-inspection",
    title: "SITE INSPECTION",
    number: "WHOOP-FRM-020",
    group: "Inspection",
    description:
      "The lift area, the ground, the zone. Not the whole civil site. 3.5.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: SITE_INSPECT_ITEMS },
      { type: "powerlines" },
      { type: "weather" },
      { type: "emergency" },
      { type: "hazard" },
      { type: "control" },
      { type: "corrective" },
      { type: "photo" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "weekly-maintenance",
    title: "WEEKLY MAINTENANCE",
    number: "WHOOP-FRM-025",
    group: "Inspection",
    description:
      "Frequent inspection. Wire rope, leaks, pins, safety devices. 14.13.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: WEEKLY_MAINT_ITEMS },
      { type: "log" },
      { type: "corrective" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "monthly-maintenance",
    title: "MONTHLY MAINTENANCE",
    number: "WHOOP-FRM-026",
    group: "Inspection",
    description:
      "Periodic inspection. Structure, rope, brakes, LMI, certificates. 14.13.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: MONTHLY_MAINT_ITEMS },
      { type: "log" },
      { type: "corrective" },
      { type: "photo" },
      { type: "comments" },
      { type: "signature" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "equipment-defect",
    title: "EQUIPMENT DEFECT REPORT",
    number: "WHOOP-FRM-022",
    group: "Inspection",
    description: "Out of service is immediate. Not next Tuesday.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: CRANE_INSPECT_ITEMS },
      { type: "corrective" },
      { type: "photo" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "incident-report",
    title: "INCIDENT REPORT",
    number: "WHOOP-FRM-010",
    group: "Incident",
    description: "Facts. We do not hide the dent.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "crane" },
      { type: "load" },
      { type: "incident" },
      { type: "photo" },
      { type: "emergency" },
      { type: "corrective" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "near-miss",
    title: "NEAR-MISS REPORT",
    number: "WHOOP-FRM-011",
    group: "Incident",
    description: "Someone in the zone. A sling that started to cut.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "hazard" },
      { type: "control" },
      { type: "comments" },
      { type: "photo" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "first-aid",
    title: "FIRST AID REPORT",
    number: "WHOOP-FRM-012",
    group: "Incident",
    description: "Site first aid and WHOOP. Regulator as the law requires.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "emergency" },
      { type: "incident" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "return-to-work",
    title: "RETURN-TO-WORK PLAN",
    number: "WHOOP-FRM-RTW",
    group: "Worker",
    description: "Restrictions named. Work matched. Not a paper promise.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "corrective" },
      { type: "comments" },
      { type: "signature" },
      { type: "signature" },
    ],
  }),
];

export function getTemplate(id: string) {
  return FORM_TEMPLATES.find((f) => f.id === id);
}
