import type { SafetyForm } from "./types";

export const FORMS: SafetyForm[] = [
  {
    slug: "flha",
    title: "FLHA",
    number: "WHOOP-FRM-001",
    group: "Daily",
    summary: "Field level hazard assessment for this shift, this lift, this ground.",
    when: "Start of shift and whenever the work, weather, crew or zone changes.",
    fields: [
      "Site, date, crane, crew names and roles",
      "Task and load",
      "Hazards named",
      "Controls",
      "Stop criteria",
      "Signatures of everyone on the lift",
    ],
    routing: "Crew completes in the field. Copy to WHOOP.",
  },
  {
    slug: "crane-pre-use",
    title: "CRANE PRE-USE INSPECTION",
    number: "WHOOP-FRM-002",
    group: "Daily",
    summary: "Operator inspection for this shift, this machine, this configuration.",
    when: "Before the crane comes on load, every shift.",
    fields: [
      "Machine identity and configuration",
      "Walkaround and function tests",
      "LMI / RCI, brakes, outriggers, wire rope, hooks",
      "Defects and out-of-service decision",
      "Operator name and time",
    ],
    routing: "Operator completes. Defects that affect lifting stop the crane and notify WHOOP and the site.",
  },
  {
    slug: "rigging-inspection-form",
    title: "RIGGING INSPECTION",
    number: "WHOOP-FRM-003",
    group: "Daily",
    summary: "Sling and hardware check before the hitch takes load.",
    when: "Before use, and when gear is returned to the pile.",
    fields: [
      "Item, type, WLL, identification",
      "Condition (pass / fail)",
      "If fail: tag number, isolation, who was told",
      "Inspector name",
    ],
    routing: "Rigger or competent person. Failed gear is isolated the same hour.",
  },
  {
    slug: "toolbox-meeting",
    title: "TOOLBOX MEETING",
    number: "WHOOP-FRM-004",
    group: "Daily",
    summary: "The brief for this crew, this lift, this day — not a safety poster reading.",
    download: {
      href: "https://www.bccsa.ca/resources.php?id_catalogue=1",
      label: "BCCSA TOOLBOX TALKS →",
      note: "Use the crane and rigging ones: chain and sling, crush and pinch, struck-by, electrical, heat, cold machines, loading and unloading, mounting and dismounting, communication, working alone, JHA, incident and near miss. Skip silica, excavation, forklift and skid steer unless that is actually the work. Sign in on bccsa.ca to download.",
      external: true,
    },
    when: "Start of shift and before a change of plan.",
    fields: [
      "Date, site, attendees",
      "Today’s lifts and known hazards",
      "Signals, radios, stop word",
      "Questions and answers",
      "Attendance",
    ],
    routing: "Supervisor or designated lead. Copy to WHOOP with the FLHA.",
  },
  {
    slug: "daily-lift-checklist",
    title: "DAILY LIFT CHECKLIST",
    number: "WHOOP-FRM-005",
    group: "Daily",
    summary: "The last pass before the hook: plan, gear, zone, people.",
    when: "Before the first load of the shift and before each non-routine lift.",
    fields: [
      "Load data confirmed",
      "Chart and configuration",
      "Rigging inspected",
      "Zone held",
      "Communication tested",
      "Go / no-go",
    ],
    routing: "Operator and rigger initial. Supervisor holds the sheet.",
  },
  {
    slug: "lift-plan",
    title: "LIFT PLAN",
    number: "WHOOP-FRM-006",
    group: "Lifting",
    summary: "The written plan for a lift that is more than a routine pick.",
    when: "Non-routine lifts, tight sites, and any lift the supervisor or operator calls for a plan.",
    fields: [
      "Load weight, COG, dimensions, lifting points",
      "Crane, configuration, radius, chart capacity",
      "Rigging method and WLL",
      "Path, set point, exclusion zone",
      "Named crew",
      "Weather and abort criteria",
    ],
    routing: "Prepared before the lift. Stays at the lift.",
  },
  {
    slug: "critical-lift-plan",
    title: "CRITICAL LIFT PLAN",
    number: "WHOOP-FRM-007",
    group: "Lifting",
    summary: "Named supervision, slower brief, hard limits. Ego is not a control.",
    when: "Loads approaching chart, tandem lifts, lifts over plant or public, shifting COG, or as the site defines.",
    fields: [
      "Why it is critical",
      "Engineer involvement if required",
      "Step-by-step sequence",
      "Hold points",
      "Rescue / abort",
      "Approvals",
    ],
    routing: "Approved before the hook is loaded. Copy to WHOOP and the prime contractor as required.",
  },
  {
    slug: "rigging-plan",
    title: "RIGGING PLAN",
    number: "WHOOP-FRM-008",
    group: "Lifting",
    summary: "Hitch, hardware, angles, softeners, tag lines — written, not remembered.",
    when: "Complex hitches, multi-leg bridles, below-the-hook gear, or unknown COG.",
    fields: [
      "Hitch type and sketch",
      "Sling type, length, WLL, angle",
      "Hardware list",
      "Edge protection",
      "Tag line plan",
    ],
    routing: "Rigger and supervisor. Attached to the lift plan.",
  },
  {
    slug: "pre-lift-meeting",
    title: "PRE-LIFT MEETING",
    number: "WHOOP-FRM-009",
    group: "Lifting",
    summary: "Everyone on the lift can repeat the plan, the signals, who stops it, and where they stand.",
    when: "Before a critical or non-routine lift, and whenever the crew changes.",
    fields: [
      "Attendees and roles",
      "Sequence",
      "Signals and radios",
      "Zone",
      "Abort",
      "Questions",
    ],
    routing: "Held at the lift. Record kept with the plan.",
  },
  {
    slug: "incident-report",
    title: "INCIDENT REPORT",
    number: "WHOOP-FRM-010",
    group: "Incident",
    summary: "Facts: what, where, when, who, what gear, what was supposed to happen.",
    when: "Any injury, dropped load, crane contact, property damage, or serious stop-work.",
    fields: [
      "Date, time, site",
      "People involved and witnesses",
      "Crane and rigging",
      "Description",
      "Immediate actions",
      "Notifications",
    ],
    routing: "WHOOP immediately for serious events. See Report an Incident.",
  },
  {
    slug: "near-miss-report",
    title: "NEAR-MISS REPORT",
    number: "WHOOP-FRM-011",
    group: "Incident",
    summary: "What almost happened, and what will change so it does not.",
    when: "Same shift as the near miss.",
    fields: [
      "Event",
      "What prevented the injury or drop",
      "Gear and conditions",
      "Suggested control",
    ],
    routing: "WHOOP same day. See Report a Near Miss.",
  },
  {
    slug: "first-aid-report",
    title: "FIRST AID REPORT",
    number: "WHOOP-FRM-012",
    group: "Incident",
    summary: "Care given, by whom, and whether the person stayed on shift.",
    when: "Any first aid involving a WHOOP worker.",
    fields: [
      "Injured person",
      "Nature of injury",
      "Treatment",
      "Attendant",
      "WorkSafeBC / site first aid log as required",
    ],
    routing: "Site first aid and WHOOP. Regulator as the law requires.",
  },
  {
    slug: "investigation",
    title: "INVESTIGATION",
    number: "WHOOP-FRM-013",
    group: "Incident",
    summary: "Causes, not a defence brief. What the program will change.",
    when: "After an incident involving WHOOP personnel, on a timeline that matches severity.",
    fields: [
      "Sequence of events",
      "Scene, photographs, gear held",
      "Witness names and statements",
      "Conditions and decisions",
      "Root and contributing causes",
      "Actions with owners and dates",
      "Closure and verification",
    ],
    routing: "WHOOP Safety. Shared with the client as required.",
  },
  {
    slug: "corrective-action",
    title: "CORRECTIVE ACTION",
    number: "WHOOP-FRM-014",
    group: "Incident",
    summary: "Finding → action → person → due date → done → verified.",
    when: "Every finding from an inspection, incident or near miss that requires a change.",
    fields: [
      "Finding",
      "Action",
      "Responsible person",
      "Due date",
      "Completion",
      "Verification",
    ],
    routing: "Tracked in Inspections and Corrective Actions.",
  },
  {
    slug: "orientation",
    title: "ORIENTATION",
    number: "WHOOP-FRM-015",
    group: "Worker",
    summary: "This program, this dispatch, this site — including young or new worker topics in 3.23.",
    when: "First WHOOP dispatch, when the role or workplace hazards change, and before a young or new worker begins (3.22–3.25).",
    fields: [
      "Worker name, role, date of birth if under 25",
      "Supervisor name and contact",
      "Program, rights (including refusal), company rules",
      "Hazards of this workplace, working alone, violence",
      "PPE, first aid, emergency, WHMIS as it applies",
      "Task instruction and demonstration",
      "Committee or worker-rep contact as applicable",
      "Host site orientation completed",
      "Tickets on file",
    ],
    routing: "WHOOP before or at first dispatch.",
    download: {
      href: "/safety/builder/orientation",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "training-record",
    title: "TRAINING RECORD",
    number: "WHOOP-FRM-016",
    group: "Worker",
    summary: "What was completed, when, and when it expires.",
    when: "Whenever a qualification, orientation or briefing is completed.",
    fields: [
      "Course or briefing",
      "Provider",
      "Date",
      "Expiry",
      "Evidence",
    ],
    routing: "WHOOP worker file.",
  },
  {
    slug: "competency-assessment",
    title: "COMPETENCY ASSESSMENT",
    number: "WHOOP-FRM-017",
    group: "Worker",
    summary: "Can this person do this work on this class of machine, today.",
    when: "Before first placement in a role, and when the work class changes.",
    fields: [
      "Role (operator / rigger / signalperson / supervisor)",
      "Machine or task class",
      "Observations",
      "Result and restrictions",
      "Assessor",
    ],
    routing: "WHOOP. Matched to the work before dispatch.",
  },
  {
    slug: "ppe-issue",
    title: "PPE ISSUE",
    number: "WHOOP-FRM-018",
    group: "Worker",
    summary: "What was issued, inspected, replaced, and who has it.",
    when: "On issue, on inspection, and on return or replacement.",
    fields: [
      "Item",
      "Condition / inspection result",
      "Worker",
      "Date",
      "Replaced or destroyed if failed",
    ],
    routing: "WHOOP. Failed PPE is destroyed or marked, not left in a truck.",
  },
  {
    slug: "worker-acknowledgement",
    title: "WORKER ACKNOWLEDGEMENT",
    number: "WHOOP-FRM-019",
    group: "Worker",
    summary: "The worker has read this program and knows where it lives.",
    when: "Onboarding and on each controlled revision that changes how the work is done.",
    fields: [
      "Name",
      "Date",
      "Revision acknowledged",
      "Questions asked",
    ],
    routing: "WHOOP worker file.",
  },
  {
    slug: "workplace-inspection",
    title: "SITE INSPECTION",
    number: "WHOOP-FRM-020",
    group: "Inspection",
    summary: "The lift area, the access, the zone — not the whole civil site.",
    when: "At setup. Again at a frequency matching the dispatch — at least weekly on a standing tower. After a change that could have affected the pad, the zone or the access.",
    fields: [
      "Area",
      "Findings",
      "Class (immediate / before next shift / scheduled)",
      "Risk",
      "Actions, owner, date",
    ],
    routing: "Supervisor. Actions enter the corrective-action log.",
  },
  {
    slug: "crane-inspection-form",
    title: "CRANE INSPECTION",
    number: "WHOOP-FRM-021",
    group: "Inspection",
    summary: "Beyond pre-use: defects, certificates, and whether the machine stays up.",
    when: "As assigned, and after any event that could have damaged the crane.",
    fields: [
      "Machine",
      "Inspection type",
      "Findings",
      "Certificates on site",
      "Status (in / out of service)",
    ],
    routing: "Operator / competent person. Out of service is immediate.",
  },
  {
    slug: "rigging-equipment-inspection",
    title: "RIGGING EQUIPMENT INSPECTION",
    number: "WHOOP-FRM-022",
    group: "Inspection",
    summary: "Periodic check of the WHOOP or site gear our people will pick up.",
    when: "Before a long dispatch and on a recorded interval for gear WHOOP controls.",
    fields: [
      "Inventory",
      "Condition",
      "Removed from service",
      "Inspector",
    ],
    routing: "WHOOP. Failed gear does not travel to the next site.",
  },
  {
    slug: "crane-operator-log",
    title: "CRANE OPERATOR LOG",
    number: "WHOOP-FRM-023",
    group: "Daily",
    summary:
      "Operator’s record for this machine this shift: hours, lifts, defects. Stays with the crane.",
    when: "Every shift the operator is on the machine. Before leaving the cab.",
    fields: [
      "Machine identity and hour meter",
      "Pre-use result",
      "Hours in hoisting service",
      "Work performed and number of lifts",
      "Defects and who was told",
      "Operator signature",
    ],
    routing:
      "Operator completes. Copy in the machine logbook. Copy to WHOOP with the dispatch.",
  },
  {
    slug: "rigger-log",
    title: "RIGGER LOG",
    number: "WHOOP-FRM-024",
    group: "Daily",
    summary: "Gear used, lifts made, what was isolated. Before the hitch takes load.",
    when: "Each shift the rigger is on the lift.",
    fields: [
      "Site, date, rigger",
      "Load and hitch",
      "Slings and hardware identified",
      "Pre-use of gear (pass / fail / isolated)",
      "Lifts this shift",
      "Rejected gear tagged",
    ],
    routing: "Rigger completes. Failed gear is isolated the same hour. Copy to WHOOP.",
  },
  {
    slug: "weekly-maintenance",
    title: "WEEKLY MAINTENANCE",
    number: "WHOOP-FRM-025",
    group: "Inspection",
    summary:
      "Frequent inspection: wire rope, leaks, pins, safety devices — items that change with use.",
    when: "Weekly while the crane is in service, or as the OEM requires if sooner.",
    fields: [
      "Machine identity and hours",
      "Wire rope, hook, sheaves",
      "Hydraulics, pins, fasteners",
      "Brakes and limit devices",
      "LMI / RCI function",
      "Lubrication this interval",
      "Defects and out-of-service decision",
    ],
    routing:
      "Operator or competent person. Entered in the crane logbook. Defects that affect lifting stop the crane.",
  },
  {
    slug: "monthly-maintenance",
    title: "MONTHLY MAINTENANCE",
    number: "WHOOP-FRM-026",
    group: "Inspection",
    summary:
      "Periodic inspection: structure, full rope, brakes, LMI, certificates. Not a walkaround.",
    when: "Monthly while in service, and after any event that could have damaged the crane.",
    fields: [
      "Machine identity and hours",
      "Boom / jib structure",
      "All running rope",
      "Brake test",
      "Safety device tests",
      "Annual certificate current",
      "OEM items due",
      "Inspector and supervisor",
    ],
    routing:
      "Competent person. Record in the logbook. Out of service is immediate. Annual certification is separate.",
  },
  {
    slug: "tower-pre-use",
    title: "TOWER PRE-USE INSPECTION",
    number: "WHOOP-FRM-027",
    group: "Inspection",
    summary:
      "Topless and hammerhead tower — this shift, this configuration. CSA Z248, 14.35.",
    when: "Before the crane comes on load, every shift. MDT 219 and other top-slewing towers.",
    fields: [
      "Machine serial, jib, reeving, mast, ballast",
      "Chart in the cab matches this configuration",
      "Mast, slew, jib, trolley, hoist rope, hook",
      "Limits, CCS / overload, anemometer, weathervane",
      "Access and Cab-IN if fitted",
      "Defects and out-of-service decision",
    ],
    routing:
      "Operator completes. Defects that affect lifting stop the crane. Copy in the logbook. Copy to WHOOP.",
    download: {
      href: "/safety/builder/tower-pre-use",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "luffing-jib-inspection",
    title: "LUFFING JIB INSPECTION",
    number: "WHOOP-FRM-028",
    group: "Inspection",
    summary:
      "MRH hydraulic luffer and MR rope luffer. Jib angle, luffing system, weathervane.",
    when: "Before the crane comes on load, every shift on a luffing-jib tower. After any luffing-system work.",
    fields: [
      "Machine serial and whether hydraulic (MRH) or rope (MR)",
      "Jib length, angle, reeving, ballast — chart in the cab",
      "Hydraulic rams, hoses, tank — or luffing rope, cathead, winch",
      "Hoist, slew, limits, anemometer",
      "Out-of-service jib position for this wind",
      "Defects and out-of-service decision",
    ],
    routing:
      "Operator completes. Luffing-system defects stop the crane. Copy in the logbook. Copy to WHOOP.",
    download: {
      href: "/safety/builder/luffing-jib-inspection",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "self-erect-inspection",
    title: "SELF-ERECT INSPECTION",
    number: "WHOOP-FRM-029",
    group: "Inspection",
    summary:
      "Hup, Igo and Igo T. Unfold complete, ballast locked, chart for this jib position.",
    when: "After unfold, and before the crane comes on load each shift while erected.",
    fields: [
      "Machine serial, jib position, ballast",
      "Outriggers, pads, slope",
      "Unfold complete — pins in, transport locks off",
      "Remote / cab, limits, hoist, power",
      "Weathervane / out-of-service",
      "Defects and out-of-service decision",
    ],
    routing:
      "Operator completes. Incomplete unfold or missing ballast stops the crane. Copy in the logbook. Copy to WHOOP.",
    download: {
      href: "/safety/builder/self-erect-inspection",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "tower-weekly-maintenance",
    title: "TOWER WEEKLY MAINTENANCE",
    number: "WHOOP-FRM-030",
    group: "Inspection",
    summary:
      "Frequent inspection of a tower, luffer or self-erect. Rope, leaks, limits, lubrication.",
    when: "Weekly while the crane is in service, or as the OEM lubrication chart requires if sooner.",
    fields: [
      "Machine identity and hours",
      "Hoist and trolley / luffing rope",
      "Hydraulics, pins, slew, weathervane",
      "Limits, CCS / overload, anemometer",
      "Lubrication this interval per the serial chart",
      "Defects and out-of-service decision",
    ],
    routing:
      "Operator or competent person. Entered in the crane logbook. OEM interval wins if it is sooner. Defects that affect lifting stop the crane.",
    download: {
      href: "/safety/builder/tower-weekly-maintenance",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "tower-monthly-maintenance",
    title: "TOWER MONTHLY MAINTENANCE",
    number: "WHOOP-FRM-031",
    group: "Inspection",
    summary:
      "Periodic inspection. Structure, full rope, slew bolts, hydraulics, certificates.",
    when: "Monthly while in service, and after any event that could have damaged the crane.",
    fields: [
      "Machine identity and hours",
      "Jib, mast, ties, climbing frame",
      "All running rope",
      "Slew ring check per OEM",
      "Winches, hydraulics, electrical",
      "Brake and safety-device tests",
      "Annual / comprehensive inspection current",
      "OEM items due — inspector and supervisor",
    ],
    routing:
      "Competent person. Record in the logbook. Out of service is immediate. Follow the serial maintenance manual for torque and oil specs.",
    download: {
      href: "/safety/builder/tower-monthly-maintenance",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "management-review",
    title: "MANAGEMENT OHS REVIEW",
    number: "WHOOP-FRM-032",
    group: "Inspection",
    summary: "Periodic management meeting: trends, actions, objectives. 3.3(d).",
    when: "At least quarterly, and after a serious incident.",
    fields: [
      "Date, attendees",
      "Incidents and investigations",
      "Inspection findings still open",
      "Training and competency gaps",
      "Worker concerns and refusals",
      "COR / audit actions",
      "Objectives this period",
      "Decisions, owners, dates",
    ],
    routing: "WHOOP Safety. Minutes kept with the records. Actions enter FRM-014.",
    download: {
      href: "/safety/builder/management-review",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "ohs-meeting",
    title: "OHS MEETING",
    number: "WHOOP-FRM-033",
    group: "Daily",
    summary: "Worker safety meeting. Toolbox is the lift brief. This is the OHS meeting.",
    when: "At least monthly where 3.2 applies. Otherwise with management review, and when a committee or representative meets.",
    fields: [
      "Date, workplace, attendees",
      "Unsafe conditions and practices named",
      "Incidents and near misses",
      "Inspection findings",
      "Worker concerns",
      "Actions, owners, dates",
    ],
    routing: "WHOOP or the supervisor who ran it. Record kept. 3.2(c).",
    download: {
      href: "/safety/builder/ohs-meeting",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "emergency-drill",
    title: "EMERGENCY DRILL",
    number: "WHOOP-FRM-034",
    group: "Incident",
    summary: "A drill on a workplace WHOOP controls — or a recorded site drill WHOOP people joined.",
    when: "Where WHOOP is the employer at that workplace, on an interval the emergency plan names. After a change to the plan.",
    fields: [
      "Date, workplace, scenario",
      "Who participated",
      "What was tested (first aid, muster, crane shutdown, rescue, powerline)",
      "What failed",
      "Actions, owners, dates",
    ],
    routing: "WHOOP Safety. Lessons enter FRM-014.",
    download: {
      href: "/safety/builder/emergency-drill",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "refuse-unsafe-work",
    title: "REFUSAL OF UNSAFE WORK",
    number: "WHOOP-FRM-035",
    group: "Incident",
    summary: "The right to refuse is a record, not a rumour. Work stays stopped until the danger is controlled.",
    when: "Whenever a WHOOP worker refuses work they have reasonable cause to believe is dangerous.",
    fields: [
      "Worker, date, workplace, supervisor",
      "Work refused and why — specific",
      "Who was told (site and WHOOP)",
      "Investigation and outcome",
      "When work resumed, and what changed",
    ],
    routing: "WHOOP Safety the same day. Worker is not sent home as punishment for a good-faith refusal.",
    download: {
      href: "/safety/builder/refuse-unsafe-work",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "pre-assembly-meeting",
    title: "PRE-ASSEMBLY MEETING",
    number: "WHOOP-FRM-036",
    group: "Binder",
    summary:
      "The meeting before the tower or self-erect goes up. Named people, sequence, zone, abort.",
    when: "Before erect, climb, reposition or dismantle. Before the assist crane is on load.",
    fields: [
      "Site, date, crane make / model / serial",
      "Activity (erect, climb, reposition, dismantle)",
      "Activity supervisor and lead hand",
      "Crew and assist-crane operator",
      "Sequence and hold points",
      "Exclusion zone and public interface",
      "Radios and stop word",
      "Weather abort",
      "Rescue / THARRP named",
      "Attendance and signatures",
    ],
    routing:
      "Activity supervisor runs it. Copy in the site binder. Copy with the NOP-TC file.",
    download: {
      href: "/safety/builder/pre-assembly-meeting",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "powerline-30m33",
    title: "POWERLINE RECORD — 30M33",
    number: "WHOOP-FRM-037",
    group: "Binder",
    summary:
      "Site schematic and the record of the discussion with the power-system owner. Not a substitute for Form 30M33.",
    when: "Before the crane can enter the limits of approach. When lines, voltage or the radius change.",
    fields: [
      "Site, crane, work radius",
      "Power-system owner and representative",
      "Line voltage and location (sketch)",
      "Transformers and cable hazards in the radius",
      "Limits of approach for this voltage — Table 19-1A",
      "What was agreed: displace, isolate and ground, or identify and guard",
      "30M33 number / date if issued",
      "Who holds the coded form",
      "Posted on the site board — yes / no",
    ],
    routing:
      "Completed with the utility representative. Coded 30M33 is ordered from WorkSafeBC and signed by the power-system owner. This sheet stays in the binder and on the board.",
    download: {
      href: "/safety/builder/powerline-30m33",
      label: "FILL THIS FORM →",
    },
    links: [
      {
        href: "https://www.worksafebc.com/en/resources/health-safety/forms/assurance-of-compliance-with-occupational-health-and-safety-regulation-part-19-form-30m33?lang=en",
        label: "WORKSAFEBC FORM 30M33 →",
        external: true,
        note: "Coded NCR form. Sample online. Order the working copy from WorkSafeBC. Only 30M33 is acceptable as the assurance in writing.",
      },
    ],
  },
  {
    slug: "radio-frequency",
    title: "RADIO FREQUENCY COORDINATION",
    number: "WHOOP-FRM-038",
    group: "Binder",
    summary:
      "Site radio log and the WorkSafeBC 52E73C request. Tower, self-erect and industrial cranes.",
    when: "New site. Radios change. Crane on site more than one week.",
    fields: [
      "Site, crane, dates on site",
      "Employer and contact",
      "Number of cranes and radios",
      "Requested / assigned frequencies",
      "52E73C submitted — date",
      "Assigned channel posted in the cab",
      "Tested with the rigger before the first load",
    ],
    routing:
      "Submit 52E73C to WorkSafeBC. This sheet is the site copy. Assigned channel in the cab and in the binder.",
    download: {
      href: "/safety/builder/radio-frequency",
      label: "FILL THIS FORM →",
    },
    links: [
      {
        href: "https://www.worksafebc.com/en/resources/health-safety/forms/radio-frequency-coordination-crane-operations-52e73c?lang=en",
        label: "WORKSAFEBC 52E73C PDF →",
        external: true,
        note: "Official coordination request. Download from WorkSafeBC. Mobile cranes use the mobile form, not this one.",
      },
    ],
  },
  {
    slug: "nop-tc-notice",
    title: "NOP-TC POSTING NOTICE",
    number: "WHOOP-FRM-039",
    group: "Binder",
    summary:
      "The notice posted at the workplace for the duration of the crane activity. 14.73.3.",
    when: "Before erect, climb, reposition or dismantle starts. Stays posted until that activity is done.",
    fields: [
      "Workplace address",
      "Crane make, model, serial, configuration",
      "Activity and dates",
      "Employer responsible for the activity",
      "Qualified supervisor — name and contact",
      "WorkSafeBC NOP confirmation / number",
      "Date submitted (at least two weeks before)",
      "Where posted",
    ],
    routing:
      "NOP-TC is submitted on WorkSafeBC’s online form, project type Tower Crane. This sheet is what stays on the board. Copy in the binder.",
    download: {
      href: "/safety/builder/nop-tc-notice",
      label: "FILL THIS FORM →",
    },
    links: [
      {
        href: "https://www.worksafebc.com/en/for-employers/just-for-you/submit-notice-project",
        label: "SUBMIT NOP-TC →",
        external: true,
        note: "Choose Tower Crane as the project type. Attach the binder checklist, SWPs and supervisor qualifications as the form requires.",
      },
    ],
  },
  {
    slug: "operator-orientation",
    title: "OPERATOR CRANE ORIENTATION",
    number: "WHOOP-FRM-040",
    group: "Binder",
    summary:
      "This machine, this site, this chart. A tower ticket is not an orientation.",
    when: "Before the operator takes the crane on this site. After a climb, a reconfigure, or a change of radios or rescue.",
    fields: [
      "Operator, ticket class and expiry",
      "Crane serial, jib, reeving, ballast — chart in the cab",
      "Access, Cab-IN, weathervane",
      "Radios and stop word",
      "Powerlines and 30M33 location",
      "THARRP / high-angle rescue — how to summon",
      "Wind and shutdown",
      "Who can take the crane out of service",
      "Operator and supervisor signatures",
    ],
    routing: "Supervisor walks it. Operator signs. Copy in the binder and the logbook.",
    download: {
      href: "/safety/builder/operator-orientation",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "tower-crane-report",
    title: "TOWER CRANE REPORT",
    number: "WHOOP-FRM-041",
    group: "Binder",
    summary:
      "Qualified supervisor’s report after erect, climb or reposition. Companion to the WorkSafeBC checklist.",
    when: "After the crane is erected, climbed or repositioned. Before it goes back on load.",
    fields: [
      "Site, date, activity",
      "Crane serial and configuration as standing",
      "Qualified supervisor",
      "Foundation / pads / ties as left",
      "Limits, overload, anemometer, weathervane tested",
      "Aviation lights / marking if required",
      "Deficiencies and out-of-service items",
      "Release to operate — yes / no",
    ],
    routing:
      "Activity supervisor. Keep at the workplace. WorkSafeBC’s checklist is the official format — complete that as well and file both.",
    download: {
      href: "/safety/builder/tower-crane-report",
      label: "FILL THIS FORM →",
    },
    links: [
      {
        href: "https://www.worksafebc.com/en/resources/health-safety/checklist/tower-crane-report?lang=en",
        label: "WORKSAFEBC TOWER CRANE REPORT →",
        external: true,
      },
    ],
  },
  {
    slug: "supervisor-qualification",
    title: "ACTIVITY SUPERVISOR QUALIFICATION",
    number: "WHOOP-FRM-042",
    group: "Binder",
    summary:
      "The person directing erect, climb, reposition or dismantle on this particular crane. 14.73.2.",
    when: "Named on the NOP-TC. Before the activity starts.",
    fields: [
      "Supervisor name and company",
      "This crane — make, model, serial",
      "Activity",
      "Qualifications and how they apply to this machine",
      "Registered with BC Crane Safety — yes / no / number",
      "Lead hand if used",
      "Who confirmed competency",
    ],
    routing: "Attached to the NOP-TC. Copy in the binder. The supervisor on the hook is this person, not a delegate who was not named.",
    download: {
      href: "/safety/builder/supervisor-qualification",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "csa-compliance",
    title: "CSA Z248 COMPLIANCE RECORD",
    number: "WHOOP-FRM-043",
    group: "Binder",
    summary:
      "How this serial meets CSA Z248-2004 as 14.2(6) requires. A brochure is not a declaration.",
    when: "Before the crane is placed in service on this site.",
    fields: [
      "Crane serial, year, manufacturer",
      "Document relied on (manufacturer declaration, engineer letter, certificate)",
      "Who holds the original",
      "Configuration this document covers",
      "Gaps and how they are closed",
    ],
    routing: "Owner / supplier provides. Crane user confirms it matches this machine. Binder copy.",
    download: {
      href: "/safety/builder/csa-compliance",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "tharrp-cover",
    title: "THARRP / HIGH-ANGLE RESCUE COVER",
    number: "WHOOP-FRM-044",
    group: "Binder",
    summary:
      "Who requested the survey, which fire department, how to summon them. Not a fall-protection plan.",
    when: "Before a tower operator is sent up. After a change of crane location or expected duration past 60 days on a high-rise.",
    fields: [
      "Site and crane",
      "Who requested the THARRP survey (host / prime / owner)",
      "Fire department named",
      "Portal confirmation / survey date",
      "Formal Site Survey on site if past 60 days",
      "How the operator summons rescue",
      "WHOOP confirmation date",
    ],
    routing: "Host or prime owns the portal request. WHOOP confirms before dispatch. Copy in the binder.",
    download: {
      href: "/safety/builder/tharrp-cover",
      label: "FILL THIS FORM →",
    },
    links: [
      {
        href: "https://www.bccsa.ca/tharrp_program.php",
        label: "BCCSA THARRP →",
        external: true,
      },
    ],
  },
  {
    slug: "navcan-land-use",
    title: "NAV CANADA / AERONAUTICAL FILE",
    number: "WHOOP-FRM-045",
    group: "Binder",
    summary:
      "Land-use and obstacle file for a crane that can affect aviation. Portal submissions, not a WHOOP permit.",
    when: "When the crane may be an obstacle or sits in airport zoning. Start weeks before the erect.",
    fields: [
      "Site coordinates and tip height",
      "Dates the crane will be up",
      "NAV CANADA submission / file number",
      "Transport Canada AAF / file number",
      "Marking and lighting required",
      "NOTAM contacts",
      "Airport authority if they have their own process",
    ],
    routing: "Owner or prime submits. Copies in the binder. Lighting failures go to a NAV CANADA FIC.",
    download: {
      href: "/safety/builder/navcan-land-use",
      label: "FILL THIS FORM →",
    },
    links: [
      {
        href: "https://www.navcanada.ca/en/aeronautical-information/land-use-program.aspx",
        label: "NAV CANADA LAND USE →",
        external: true,
      },
      {
        href: "https://tc.canada.ca/en/aviation/general-operating-flight-rules/marking-lighting-obstacles-air-navigation",
        label: "TRANSPORT CANADA AAF →",
        external: true,
      },
    ],
  },
  {
    slug: "power-source",
    title: "POWER SOURCE RECORD",
    number: "WHOOP-FRM-046",
    group: "Binder",
    summary: "How the crane is fed, who can isolate it, where the earth is.",
    when: "Before first power-up on this site. After any change to the feed.",
    fields: [
      "Supply (generator / site / utility)",
      "Voltage, phases, protection",
      "Isolation point and lockout",
      "Earthing",
      "Who is allowed to make it live",
      "Who holds the keys",
    ],
    routing: "Activity supervisor and the person who made the connection. Copy in the binder. Lockout: SWP-026.",
    download: {
      href: "/safety/builder/power-source",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "site-layout",
    title: "SITE LAYOUT COVER",
    number: "WHOOP-FRM-047",
    group: "Binder",
    summary:
      "Cover sheet for the drawing package: radius, slew, public, adjacent cranes. Attach the drawings.",
    when: "With the NOP-TC. After any change to standing position or configuration.",
    fields: [
      "Drawing numbers and revision",
      "Crane standing position",
      "Maximum radius and height",
      "Adjacent cranes / anti-collision",
      "Public interface",
      "Access to the machine",
    ],
    routing: "Design / site package in the binder behind this sheet.",
    download: {
      href: "/safety/builder/site-layout",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "traffic-permits",
    title: "TRAFFIC AND STREET-USE PERMITS",
    number: "WHOOP-FRM-048",
    group: "Binder",
    summary: "Cover sheet for municipal permits. The city paper sits behind it.",
    when: "Whenever the crane or the erect occupies a street, lane or sidewalk.",
    fields: [
      "Municipality",
      "Permit numbers and dates",
      "Lane / sidewalk / hoist-over-street",
      "Traffic control contractor",
      "Hours in force",
    ],
    routing: "Prime or owner holds the permit. Copy in the binder.",
    download: {
      href: "/safety/builder/traffic-permits",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "ndt-record",
    title: "NDT RECORD",
    number: "WHOOP-FRM-049",
    group: "Binder",
    summary: "Cover sheet for the current non-destructive testing report on this serial.",
    when: "Before the components go in the air. When the report expires or the components change.",
    fields: [
      "Crane serial and components covered",
      "Testing company",
      "Report number and date",
      "Method (UT, MT, other)",
      "Result and next due",
      "Who holds the original",
    ],
    routing: "Owner / supplier. Binder copy. Failed components do not go up.",
    download: {
      href: "/safety/builder/ndt-record",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "hoist-rope-record",
    title: "HOIST ROPE RECORD",
    number: "WHOOP-FRM-050",
    group: "Binder",
    summary: "The rope on the drum: mill cert, date on, hours, condition.",
    when: "When rope is installed. Updated on the inspection interval. When it comes off.",
    fields: [
      "Crane serial, drum, rope specification",
      "Mill cert / identification",
      "Date installed, hours at install",
      "Lubrication",
      "Broken wires / condition this inspection",
      "Date removed and reason",
    ],
    routing: "Competent person. With the mill cert in the binder. Logbook entry.",
    download: {
      href: "/safety/builder/hoist-rope-record",
      label: "FILL THIS FORM →",
    },
  },
  {
    slug: "operator-certification",
    title: "OPERATOR CERTIFICATION FILE",
    number: "WHOOP-FRM-051",
    group: "Binder",
    summary:
      "Cover sheet for the operator’s BC Crane Safety certificate and, if provisional, the supervision plan.",
    when: "Before the operator takes this crane. When the ticket or the supervision plan changes.",
    fields: [
      "Operator name",
      "Certificate class and number",
      "Expiry",
      "Provisional — yes / no",
      "Supervision plan attached — if provisional",
      "This crane class matches the ticket",
    ],
    routing: "Copy of the ticket behind this sheet. Provisional: WorkSafeBC supervision-plan template as well.",
    download: {
      href: "/safety/builder/operator-certification",
      label: "FILL THIS FORM →",
    },
    links: [
      {
        href: "https://bccranesafety.ca/",
        label: "BC CRANE SAFETY →",
        external: true,
      },
    ],
  },
];

export function getForm(slug: string) {
  return FORMS.find((item) => item.slug === slug);
}

export const FORM_GROUPS = [
  "Daily",
  "Lifting",
  "Incident",
  "Worker",
  "Inspection",
  "Binder",
] as const;
