import type { SafetyForm } from "./types";

export const FORMS: SafetyForm[] = [
  {
    slug: "flha",
    title: "FLHA",
    number: "WHOOP-FRM-001",
    group: "Daily",
    summary: "Field level hazard assessment for this shift, this lift, this ground.",
    when: "Start of shift and whenever the work, weather, crew or zone changes.",
    fields: [
      "Site, date, crane, crew names and roles",
      "Task and load",
      "Hazards named",
      "Controls",
      "Stop criteria",
      "Signatures of everyone on the lift",
    ],
    routing: "Crew completes in the field. Copy to WHOOP.",
  },
  {
    slug: "crane-pre-use",
    title: "CRANE PRE-USE INSPECTION",
    number: "WHOOP-FRM-002",
    group: "Daily",
    summary: "Operator inspection for this shift, this machine, this configuration.",
    when: "Before the crane comes on load, every shift.",
    fields: [
      "Machine identity and configuration",
      "Walkaround and function tests",
      "LMI / RCI, brakes, outriggers, wire rope, hooks",
      "Defects and out-of-service decision",
      "Operator name and time",
    ],
    routing: "Operator completes. Defects that affect lifting stop the crane and notify WHOOP and the site.",
  },
  {
    slug: "rigging-inspection-form",
    title: "RIGGING INSPECTION",
    number: "WHOOP-FRM-003",
    group: "Daily",
    summary: "Sling and hardware check before the hitch takes load.",
    when: "Before use, and when gear is returned to the pile.",
    fields: [
      "Item, type, WLL, identification",
      "Condition (pass / fail)",
      "If fail: tag number, isolation, who was told",
      "Inspector name",
    ],
    routing: "Rigger or competent person. Failed gear is isolated the same hour.",
  },
  {
    slug: "toolbox-meeting",
    title: "TOOLBOX MEETING",
    number: "WHOOP-FRM-004",
    group: "Daily",
    summary: "The brief for this crew, this lift, this day — not a safety poster reading.",
    when: "Start of shift and before a change of plan.",
    fields: [
      "Date, site, attendees",
      "Today’s lifts and known hazards",
      "Signals, radios, stop word",
      "Questions and answers",
      "Attendance",
    ],
    routing: "Supervisor or designated lead. Copy to WHOOP with the FLHA.",
  },
  {
    slug: "daily-lift-checklist",
    title: "DAILY LIFT CHECKLIST",
    number: "WHOOP-FRM-005",
    group: "Daily",
    summary: "The last pass before the hook: plan, gear, zone, people.",
    when: "Before the first load of the shift and before each non-routine lift.",
    fields: [
      "Load data confirmed",
      "Chart and configuration",
      "Rigging inspected",
      "Zone held",
      "Communication tested",
      "Go / no-go",
    ],
    routing: "Operator and rigger initial. Supervisor holds the sheet.",
  },
  {
    slug: "lift-plan",
    title: "LIFT PLAN",
    number: "WHOOP-FRM-006",
    group: "Lifting",
    summary: "The written plan for a lift that is more than a routine pick.",
    when: "Non-routine lifts, tight sites, and any lift the supervisor or operator calls for a plan.",
    fields: [
      "Load weight, COG, dimensions, lifting points",
      "Crane, configuration, radius, chart capacity",
      "Rigging method and WLL",
      "Path, set point, exclusion zone",
      "Named crew",
      "Weather and abort criteria",
    ],
    routing: "Prepared before the lift. Stays at the lift.",
  },
  {
    slug: "critical-lift-plan",
    title: "CRITICAL LIFT PLAN",
    number: "WHOOP-FRM-007",
    group: "Lifting",
    summary: "Named supervision, slower brief, hard limits. Ego is not a control.",
    when: "Loads approaching chart, tandem lifts, lifts over plant or public, shifting COG, or as the site defines.",
    fields: [
      "Why it is critical",
      "Engineer involvement if required",
      "Step-by-step sequence",
      "Hold points",
      "Rescue / abort",
      "Approvals",
    ],
    routing: "Approved before the hook is loaded. Copy to WHOOP and the prime contractor as required.",
  },
  {
    slug: "rigging-plan",
    title: "RIGGING PLAN",
    number: "WHOOP-FRM-008",
    group: "Lifting",
    summary: "Hitch, hardware, angles, softeners, tag lines — written, not remembered.",
    when: "Complex hitches, multi-leg bridles, below-the-hook gear, or unknown COG.",
    fields: [
      "Hitch type and sketch",
      "Sling type, length, WLL, angle",
      "Hardware list",
      "Edge protection",
      "Tag line plan",
    ],
    routing: "Rigger and supervisor. Attached to the lift plan.",
  },
  {
    slug: "pre-lift-meeting",
    title: "PRE-LIFT MEETING",
    number: "WHOOP-FRM-009",
    group: "Lifting",
    summary: "Everyone on the lift can repeat the plan, the signals, who stops it, and where they stand.",
    when: "Before a critical or non-routine lift, and whenever the crew changes.",
    fields: [
      "Attendees and roles",
      "Sequence",
      "Signals and radios",
      "Zone",
      "Abort",
      "Questions",
    ],
    routing: "Held at the lift. Record kept with the plan.",
  },
  {
    slug: "incident-report",
    title: "INCIDENT REPORT",
    number: "WHOOP-FRM-010",
    group: "Incident",
    summary: "Facts: what, where, when, who, what gear, what was supposed to happen.",
    when: "Any injury, dropped load, crane contact, property damage, or serious stop-work.",
    fields: [
      "Date, time, site",
      "People involved and witnesses",
      "Crane and rigging",
      "Description",
      "Immediate actions",
      "Notifications",
    ],
    routing: "WHOOP immediately for serious events. See Report an Incident.",
  },
  {
    slug: "near-miss-report",
    title: "NEAR-MISS REPORT",
    number: "WHOOP-FRM-011",
    group: "Incident",
    summary: "What almost happened, and what will change so it does not.",
    when: "Same shift as the near miss.",
    fields: [
      "Event",
      "What prevented the injury or drop",
      "Gear and conditions",
      "Suggested control",
    ],
    routing: "WHOOP same day. See Report a Near Miss.",
  },
  {
    slug: "first-aid-report",
    title: "FIRST AID REPORT",
    number: "WHOOP-FRM-012",
    group: "Incident",
    summary: "Care given, by whom, and whether the person stayed on shift.",
    when: "Any first aid involving a WHOOP worker.",
    fields: [
      "Injured person",
      "Nature of injury",
      "Treatment",
      "Attendant",
      "WorkSafeBC / site first aid log as required",
    ],
    routing: "Site first aid and WHOOP. Regulator as the law requires.",
  },
  {
    slug: "investigation",
    title: "INVESTIGATION",
    number: "WHOOP-FRM-013",
    group: "Incident",
    summary: "Causes, not a defence brief. What the program will change.",
    when: "After an incident involving WHOOP personnel, on a timeline that matches severity.",
    fields: [
      "Sequence of events",
      "Conditions and decisions",
      "Root and contributing causes",
      "Actions with owners and dates",
    ],
    routing: "WHOOP Safety. Shared with the client as required.",
  },
  {
    slug: "corrective-action",
    title: "CORRECTIVE ACTION",
    number: "WHOOP-FRM-014",
    group: "Incident",
    summary: "Finding → action → person → due date → done → verified.",
    when: "Every finding from an inspection, incident or near miss that requires a change.",
    fields: [
      "Finding",
      "Action",
      "Responsible person",
      "Due date",
      "Completion",
      "Verification",
    ],
    routing: "Tracked in Inspections and Corrective Actions.",
  },
  {
    slug: "orientation",
    title: "ORIENTATION",
    number: "WHOOP-FRM-015",
    group: "Worker",
    summary: "This program, this dispatch, this site’s known rules — before the hook.",
    when: "First WHOOP dispatch and when the program or role changes.",
    fields: [
      "Worker name and role",
      "Program acknowledgement",
      "Site orientation completed",
      "Tickets on file",
    ],
    routing: "WHOOP before or at first dispatch.",
  },
  {
    slug: "training-record",
    title: "TRAINING RECORD",
    number: "WHOOP-FRM-016",
    group: "Worker",
    summary: "What was completed, when, and when it expires.",
    when: "Whenever a qualification, orientation or briefing is completed.",
    fields: [
      "Course or briefing",
      "Provider",
      "Date",
      "Expiry",
      "Evidence",
    ],
    routing: "WHOOP worker file.",
  },
  {
    slug: "competency-assessment",
    title: "COMPETENCY ASSESSMENT",
    number: "WHOOP-FRM-017",
    group: "Worker",
    summary: "Can this person do this work on this class of machine, today.",
    when: "Before first placement in a role, and when the work class changes.",
    fields: [
      "Role (operator / rigger / signalperson / supervisor)",
      "Machine or task class",
      "Observations",
      "Result and restrictions",
      "Assessor",
    ],
    routing: "WHOOP. Matched to the work before dispatch.",
  },
  {
    slug: "ppe-issue",
    title: "PPE ISSUE",
    number: "WHOOP-FRM-018",
    group: "Worker",
    summary: "What was issued, in what condition, and who has it.",
    when: "On issue and on return or replacement.",
    fields: [
      "Item",
      "Condition",
      "Worker",
      "Date",
    ],
    routing: "WHOOP. Failed PPE is destroyed or marked, not left in a truck.",
  },
  {
    slug: "worker-acknowledgement",
    title: "WORKER ACKNOWLEDGEMENT",
    number: "WHOOP-FRM-019",
    group: "Worker",
    summary: "The worker has read this program and knows where it lives.",
    when: "Onboarding and on each controlled revision that changes how the work is done.",
    fields: [
      "Name",
      "Date",
      "Revision acknowledged",
      "Questions asked",
    ],
    routing: "WHOOP worker file.",
  },
  {
    slug: "workplace-inspection",
    title: "SITE INSPECTION",
    number: "WHOOP-FRM-020",
    group: "Inspection",
    summary: "The lift area, the access, the zone — not the whole civil site.",
    when: "At setup and at a frequency matching the duration of the dispatch.",
    fields: [
      "Area",
      "Findings",
      "Risk",
      "Actions",
    ],
    routing: "Supervisor. Actions enter the corrective-action log.",
  },
  {
    slug: "crane-inspection-form",
    title: "CRANE INSPECTION",
    number: "WHOOP-FRM-021",
    group: "Inspection",
    summary: "Beyond pre-use: defects, certificates, and whether the machine stays up.",
    when: "As assigned, and after any event that could have damaged the crane.",
    fields: [
      "Machine",
      "Inspection type",
      "Findings",
      "Certificates on site",
      "Status (in / out of service)",
    ],
    routing: "Operator / competent person. Out of service is immediate.",
  },
  {
    slug: "rigging-equipment-inspection",
    title: "RIGGING EQUIPMENT INSPECTION",
    number: "WHOOP-FRM-022",
    group: "Inspection",
    summary: "Periodic check of the WHOOP or site gear our people will pick up.",
    when: "Before a long dispatch and on a recorded interval for gear WHOOP controls.",
    fields: [
      "Inventory",
      "Condition",
      "Removed from service",
      "Inspector",
    ],
    routing: "WHOOP. Failed gear does not travel to the next site.",
  },
  {
    slug: "crane-operator-log",
    title: "CRANE OPERATOR LOG",
    number: "WHOOP-FRM-023",
    group: "Daily",
    summary:
      "Operator’s record for this machine this shift: hours, lifts, defects. Stays with the crane.",
    when: "Every shift the operator is on the machine. Before leaving the cab.",
    fields: [
      "Machine identity and hour meter",
      "Pre-use result",
      "Hours in hoisting service",
      "Work performed and number of lifts",
      "Defects and who was told",
      "Operator signature",
    ],
    routing:
      "Operator completes. Copy in the machine logbook. Copy to WHOOP with the dispatch.",
  },
  {
    slug: "rigger-log",
    title: "RIGGER LOG",
    number: "WHOOP-FRM-024",
    group: "Daily",
    summary: "Gear used, lifts made, what was isolated. Before the hitch takes load.",
    when: "Each shift the rigger is on the lift.",
    fields: [
      "Site, date, rigger",
      "Load and hitch",
      "Slings and hardware identified",
      "Pre-use of gear (pass / fail / isolated)",
      "Lifts this shift",
      "Rejected gear tagged",
    ],
    routing: "Rigger completes. Failed gear is isolated the same hour. Copy to WHOOP.",
  },
  {
    slug: "weekly-maintenance",
    title: "WEEKLY MAINTENANCE",
    number: "WHOOP-FRM-025",
    group: "Inspection",
    summary:
      "Frequent inspection: wire rope, leaks, pins, safety devices — items that change with use.",
    when: "Weekly while the crane is in service, or as the OEM requires if sooner.",
    fields: [
      "Machine identity and hours",
      "Wire rope, hook, sheaves",
      "Hydraulics, pins, fasteners",
      "Brakes and limit devices",
      "LMI / RCI function",
      "Lubrication this interval",
      "Defects and out-of-service decision",
    ],
    routing:
      "Operator or competent person. Entered in the crane logbook. Defects that affect lifting stop the crane.",
  },
  {
    slug: "monthly-maintenance",
    title: "MONTHLY MAINTENANCE",
    number: "WHOOP-FRM-026",
    group: "Inspection",
    summary:
      "Periodic inspection: structure, full rope, brakes, LMI, certificates. Not a walkaround.",
    when: "Monthly while in service, and after any event that could have damaged the crane.",
    fields: [
      "Machine identity and hours",
      "Boom / jib structure",
      "All running rope",
      "Brake test",
      "Safety device tests",
      "Annual certificate current",
      "OEM items due",
      "Inspector and supervisor",
    ],
    routing:
      "Competent person. Record in the logbook. Out of service is immediate. Annual certification is separate.",
  },
];

export function getForm(slug: string) {
  return FORMS.find((item) => item.slug === slug);
}

export const FORM_GROUPS = ["Daily", "Lifting", "Incident", "Worker", "Inspection"] as const;
