import type { Step } from "@/lib/safety";
import type { Swp } from "./types";
import { CREW_ROLES, LIFT_PPE, LIFT_REFS } from "./meta";

function swp(
  number: string,
  slug: string,
  title: string,
  summary: string,
  fields: {
    purpose: string;
    scope: string;
    competency: string[];
    hazards: string[];
    controls: string[];
    equipment: string[];
    procedure: Step[];
    prohibited: string[];
    emergency?: string;
    documentation?: string[];
  }
): Swp {
  return {
    slug,
    title,
    number,
    summary,
    purpose: fields.purpose,
    scope: fields.scope,
    responsibilities: CREW_ROLES,
    competency: fields.competency,
    hazards: fields.hazards,
    controls: fields.controls,
    ppe: LIFT_PPE,
    equipment: fields.equipment,
    procedure: fields.procedure,
    prohibited: fields.prohibited,
    emergency:
      fields.emergency ??
      "Stop the lift. Make people safe. Land or hold the load if it can be done without a second incident. First aid. Notify the site and WHOOP. Hold the scene.",
    documentation: fields.documentation ?? [
      "FLHA",
      "Pre-use / inspection record",
      "This SWP number and revision",
    ],
    references: LIFT_REFS,
  };
}

export const SWPS: Swp[] = [
  swp("WHOOP-SWP-001", "mobile-crane-setup", "MOBILE CRANE SETUP", "Put the crane on the ground the chart requires.", {
    purpose: "Set up a mobile crane so it can lift to the chart, on ground that can hold it, with a swing that will not hit people or plant.",
    scope: "Mobile cranes and boom trucks WHOOP operators are dispatched onto. Not tower erection. Not a substitute for the manufacturer’s setup.",
    competency: ["BC Crane Safety certificate for the class", "Competency on this configuration", "Able to read this chart"],
    hazards: ["Soft or unknown ground", "Buried services", "Slope", "Overhead lines", "Tail swing", "Outrigger failure", "Wrong counterweight"],
    controls: ["Walk the pad", "Locate services", "Mats", "Full extension unless the chart allows otherwise", "Level within manufacturer limit", "Swing check"],
    equipment: ["The dispatched crane", "Mats / cribbing as the plan", "Level", "Chart for this configuration"],
    procedure: [
      { n: "01", title: "CONFIRM THE MACHINE", body: "Serial, configuration, counterweight, boom, jib, tyres or tracks, software — as dispatched and as the chart." },
      { n: "02", title: "WALK THE PAD", body: "Supporting surface, excavations, cellars, backfill, underground services, slope, other cranes." },
      { n: "03", title: "POSITION", body: "Place the crane so the work is inside the chart and the swing does not take the counterweight through people or plant." },
      { n: "04", title: "OUTRIGGERS AND MATS", body: "Deploy as the chart. Mats sized for the load on the pad. Cribbing is a plan, not scrap." },
      { n: "05", title: "LEVEL", body: "Level within the manufacturer’s limit. Re-check after taking a test load if the ground can give." },
      { n: "06", title: "SWING AND LINES", body: "Boom up slowly. Confirm tail swing, boom clearance, overhead lines and other cranes." },
      { n: "07", title: "INSPECT AND BRIEF", body: "Complete pre-use. Brief signals and stop criteria. Then the hook." },
    ],
    prohibited: ["Lifting with outriggers short unless the chart for that configuration is in the cab and in use", "Setting on covers, tanks or unknown backfill", "Skipping the swing check"],
  }),
  swp("WHOOP-SWP-002", "crane-pre-use-inspection", "CRANE PRE-USE INSPECTION", "Each shift, this machine, this configuration.", {
    purpose: "Find defects that affect lifting before the crane comes on load.",
    scope: "Every WHOOP operator, every shift, on the crane they will run. Done as the manufacturer, the named 14.2 standard, and Part 14 require.",
    competency: ["Operator for this class", "Knows this machine’s inspection points"],
    hazards: ["Hidden damage", "Inoperative LMI / RCI", "Failed brakes", "Wire rope defects", "Leaks", "Missing pins"],
    controls: ["Walkaround", "Function tests", "Record defects", "Crane stays down until lifting defects are remedied"],
    equipment: ["Manufacturer inspection list", "This SWP", "Inspection form WHOOP-FRM-002"],
    procedure: [
      { n: "01", title: "IDENTITY", body: "This is the crane on the dispatch. Configuration matches the chart you will use." },
      { n: "02", title: "WALKAROUND", body: "Structure, welds, pins, tires or tracks, outriggers, leaks, rope, hook and latch, sheaves." },
      { n: "03", title: "CAB AND SAFETY DEVICES", body: "LMI / RCI, anti-two-block, horns, windows, fire extinguisher, load chart in the cab." },
      { n: "04", title: "FUNCTION", body: "Hoist, boom, swing, travel, brakes, outrigger controls — through the range you will use, without a load." },
      { n: "05", title: "RECORD", body: "Complete the inspection record. Defects that affect lifting: crane down, supervisor and WHOOP told." },
      { n: "06", title: "DO NOT START", body: "If a safety device is bypassed or inoperative, the crane does not lift." },
    ],
    prohibited: ["Signing an inspection you did not do", "Bypassing LMI / RCI or anti-two-block to “get the day going”", "Lifting with a known lifting defect"],
    documentation: ["WHOOP-FRM-002", "Machine log if the site requires it"],
  }),
  swp("WHOOP-SWP-003", "crane-operation", "CRANE OPERATION", "The chart is the law of the machine.", {
    purpose: "Operate the crane to the chart, with a crew you can hear, on a lift you can account for.",
    scope: "Mobile and tower operations WHOOP operators are dispatched to perform. Personnel lifts only where legally permitted and engineered.",
    competency: ["Certificate for the class", "Competency on this crane", "Can calculate deductions and radius"],
    hazards: ["Overload", "Side load", "Shock load", "Contact", "Lost signal", "People under the load", "Wind"],
    controls: ["Chart", "Known load", "Exclusion zone", "One signalperson", "Stop on ambiguity"],
    equipment: ["Dispatched crane", "Chart", "Working LMI / RCI", "Communication"],
    procedure: [
      { n: "01", title: "KNOW THE LIFT", body: "Weight, deductions, radius, path, set. If you cannot put it on the chart, you do not take it." },
      { n: "02", title: "CREW", body: "One signalperson. Radios or hands agreed. Stop word. Zone held." },
      { n: "03", title: "TEST", body: "Take the load just clear. Check list, boom, outriggers, ground, hitch." },
      { n: "04", title: "MOVE", body: "Smooth hoist, boom and swing. No dragging. No side loading. No shock." },
      { n: "05", title: "STOP", body: "Unclear signal, person in the zone, alarm, wind, anything that was not in the brief — stop." },
      { n: "06", title: "LAND", body: "Set on a prepared surface. Do not leave a load suspended and walk away." },
    ],
    prohibited: ["Lifting over people", "Riding the hook or load", "Using the crane as an elevator unless permitted and engineered", "Interpreting a bad signal"],
  }),
  swp("WHOOP-SWP-004", "crane-shutdown", "CRANE SHUTDOWN", "Leave the machine the way the manufacturer allows you to leave it.", {
    purpose: "Shut down so the crane cannot move, the boom is in a safe condition, and the next operator is not inheriting a trap.",
    scope: "End of shift, breaks where the operator leaves the seat, weather shutdown, and emergency shutdown as the conditions allow.",
    competency: ["Operator for this class"],
    hazards: ["Unattended controls", "Boom left in a foul", "Load left on the hook", "Wind on a raised boom", "Unauthorized access"],
    controls: ["Load landed", "Manufacturer shutdown position", "Controls isolated", "Access secured"],
    equipment: ["The crane", "Manufacturer shutdown procedure"],
    procedure: [
      { n: "01", title: "LAND THE LOAD", body: "Nothing on the hook unless a named person remains on the crane under a written hold." },
      { n: "02", title: "POSITION", body: "Boom, jib, upperworks and outriggers as the manufacturer specifies for shutdown and for the weather that is coming." },
      { n: "03", title: "ISOLATE", body: "Controls off. Keys as the site requires. House lock if fitted." },
      { n: "04", title: "ACCESS", body: "Cab closed. Ladders and gates as the site requires. Do not leave a climbing invitation." },
      { n: "05", title: "HAND OVER", body: "Defects, remaining fuel, weather, and the next lift — written or spoken to the next operator and to WHOOP if the dispatch ends." },
    ],
    prohibited: ["Leaving a load hanging for convenience", "Walking away from a running crane", "Shutdown position that fouls a line or a road"],
  }),
  swp("WHOOP-SWP-005", "crane-communication", "CRANE COMMUNICATION", "If the operator cannot hear or see the signal, the crane does not move.", {
    purpose: "Make communication a control, not a courtesy.",
    scope: "All WHOOP lifts. Hands, radio, or both. Dedicated systems where Part 14 requires them.",
    competency: ["Signalperson competency", "Operator who will not guess"],
    hazards: ["Two signalpersons", "Language mix-up", "Radio interference", "Blind corners", "Noise"],
    controls: ["One voice", "Agreed system in the brief", "Test before the hook", "Stop on loss"],
    equipment: ["Radios as specified", "High-visibility gloves for hand signals"],
    procedure: [
      { n: "01", title: "NAME THE SIGNALPERSON", body: "One person. Transfer is spoken and acknowledged." },
      { n: "02", title: "AGREE THE SYSTEM", body: "Standard hand signals and/or radio protocol. Channel, call signs, STOP." },
      { n: "03", title: "TEST", body: "Before the load. If it fails in the test, it will fail in the hole." },
      { n: "04", title: "DURING THE LIFT", body: "Operator moves only on a clear signal. Signalperson watches load, path and zone." },
      { n: "05", title: "LOSS", body: "Any break: stop. Resume only after the crew is reset." },
    ],
    prohibited: ["Two people signalling", "“He knows what I mean”", "Music or chatter on the lift channel"],
  }),
  swp("WHOOP-SWP-006", "radio-communication", "RADIO COMMUNICATION", "The lift channel is for the lift.", {
    purpose: "Use radios so the operator gets one clear instruction and a hard STOP.",
    scope: "Any WHOOP lift using radios, including blind lifts and tower operations.",
    competency: ["Can run the radio without looking at it", "Knows the stop word"],
    hazards: ["Wrong channel", "Interference", "Stepped-on transmissions", "Dead battery", "Informal language"],
    controls: ["Assigned channel", "Check before the hook", "Short commands", "Readback when it matters", "Spare battery"],
    equipment: ["Site-approved radios", "Charged batteries", "Earpiece if the site requires it"],
    procedure: [
      { n: "01", title: "CHANNEL", body: "The lift channel is posted in the brief. Not the lunch channel." },
      { n: "02", title: "CHECK", body: "Radio check operator ↔ signalperson. Confirm STOP." },
      { n: "03", title: "PROTOCOL", body: "Name who you are calling. Instruction. Wait. Operator does not move on a clipped word." },
      { n: "04", title: "STOP", body: "The word is STOP. Anyone may say it. The crane stops." },
      { n: "05", title: "FAILURE", body: "Interference or death: stop the lift. Switch to hands only if that was briefed and both can see. Otherwise the lift waits." },
    ],
    prohibited: ["Jokes on the lift channel", "Talking over STOP", "Uncharged radios at the brief"],
  }),
  swp("WHOOP-SWP-007", "standard-hand-signals", "STANDARD HAND SIGNALS", "Standard signals. Not a private dialect.", {
    purpose: "Use the hand signals the crew agreed, the ones the Board authorizes, so the operator is not translating.",
    scope: "WHOOP lifts using hand signals. Combined with radio on blind or noisy lifts as briefed.",
    competency: ["Signalperson who can demonstrate the signals", "Operator who will not invent meanings"],
    hazards: ["Non-standard signals", "Gloves that hide the hand", "Distance and glare", "Two people waving"],
    controls: ["Brief the set", "High-visibility gloves", "Position where the operator can see", "Emergency stop is unmistakable"],
    equipment: ["Gloves the operator can see"],
    procedure: [
      { n: "01", title: "AGREE", body: "The signal set is confirmed in the brief. Site-specific extras are named, not assumed." },
      { n: "02", title: "POSITION", body: "Signalperson where the operator can see both the hands and, as far as the lift allows, the load." },
      { n: "03", title: "ONE MOVEMENT", body: "One signal at a time. Hoist, boom, swing, stop — not a dance." },
      { n: "04", title: "EMERGENCY STOP", body: "Both arms out, unmistakable. Operator stops. No interpretation." },
      { n: "05", title: "TRANSFER", body: "If the signalperson must move, the operator is told. The crane waits through the transfer." },
    ],
    prohibited: ["Invented signals", "Signalling from a pocket", "Signalling while also rigging the hitch"],
  }),
  swp("WHOOP-SWP-008", "blind-lifts", "BLIND LIFTS", "Someone who can see owns the voice. The operator does not guess.", {
    purpose: "Move a load the operator cannot see without turning the crane into a rumour.",
    scope: "Any lift where the operator cannot see the load, the set, or a part of the path.",
    competency: ["Dedicated signalperson", "Tested radios", "Operator who will stop on silence"],
    hazards: ["Lost radio", "Relay chain", "Lines and people out of sight", "Boom into a structure"],
    controls: ["Named eyes", "Radio check", "Walk the path first", "Slow", "Stop on loss"],
    equipment: ["Radios", "Spotter positions", "Tag lines"],
    procedure: [
      { n: "01", title: "DECLARE IT BLIND", body: "Say it in the brief. Do not discover it at radius." },
      { n: "02", title: "NAME THE EYES", body: "Who sees the load. Who the operator listens to. One voice. Relays only with a protocol." },
      { n: "03", title: "WALK THE PATH", body: "Lines, steel, people, other cranes, holes. Before the hook is loaded." },
      { n: "04", title: "TEST COMMS", body: "Radio check. Stop word. What happens when the radio dies — written in the brief." },
      { n: "05", title: "INCH IT", body: "Slow movements. Holds. No booming through a hole nobody can see." },
      { n: "06", title: "LOST COMMS", body: "Stop. Hold or land as planned. Do not complete the last guessed instruction." },
    ],
    prohibited: ["Operator moving on a delayed relay they did not brief", "Blind lift with no dedicated signalperson"],
  }),
  swp("WHOOP-SWP-009", "rigging-inspection", "RIGGING INSPECTION", "The gear is the truth. The guess is the hazard.", {
    purpose: "Keep failed slings and hardware off the hook.",
    scope: "Every sling, shackle, hook, ring, spreader and below-the-hook device WHOOP personnel will load. Part 15 and ASME B30.9 as named.",
    competency: ["Rigger who can apply rejection criteria", "Does not need a supervisor to recognize a cut"],
    hazards: ["Unidentified gear", "Cuts, birdcaging, stretch", "Opened hooks", "Wrong pins", "Heat and chemical damage"],
    controls: ["Inspect before use", "Tag and isolate failures", "Report", "No one-more-lift"],
    equipment: ["The gear", "Rejection criteria", "Out-of-service tags", "WHOOP-FRM-003"],
    procedure: [
      { n: "01", title: "IDENTIFY", body: "Type, WLL, hitch and environment (heat, chemicals, sharp edges)." },
      { n: "02", title: "IDENTIFICATION", body: "Missing tags, illegible ratings, homemade modifications — out of service." },
      { n: "03", title: "BODY", body: "Wire rope: broken wires, kinks, birdcaging, crush, heat. Synthetic: cuts, UV, chemical, stretched stitches. Chain: nicks, stretch, gouge, seized links." },
      { n: "04", title: "HARDWARE", body: "Latch, pin engagement, wear at the saddle, opened throat, bent shackle." },
      { n: "05", title: "REMOVE OR USE", body: "Fail: tag, isolate, report on WHOOP-RPT-004. Do not leave failed gear on the pile." },
    ],
    prohibited: ["Using gear you have not inspected", "“It will be fine for this one”", "Replacing a shackle pin with a bolt from the truck"],
    documentation: ["WHOOP-FRM-003", "Damaged rigging report if it fails"],
  }),
  swp("WHOOP-SWP-010", "sling-selection", "SLING SELECTION", "The hitch chooses the sling. The leftover in the truck does not.", {
    purpose: "Pick a sling that can take the tension at this angle, in this hitch, on this edge, in this environment.",
    scope: "Wire rope, chain and synthetic slings used by WHOOP riggers.",
    competency: ["Can calculate tension for the hitch", "Knows WLL, angle and environmental limits"],
    hazards: ["Wrong type for heat or chemicals", "Angle ignored", "Choker on a capacity meant for basket", "Sharp edges"],
    controls: ["Known load", "Known hitch", "Angle calculation", "Manufacturer table", "Edge protection"],
    equipment: ["Identified slings", "WLL tags", "Softeners"],
    procedure: [
      { n: "01", title: "LOAD", body: "Weight and COG. If unknown, stop." },
      { n: "02", title: "HITCH", body: "Vertical, choker or basket. Capacity changes. Do not mix them in your head." },
      { n: "03", title: "ANGLE", body: "θ from the horizontal. Tension = share / sin θ for a two-leg bridle. Below 30° is not a WHOOP hitch unless an engineer owns it." },
      { n: "04", title: "ENVIRONMENT", body: "Heat, chemicals, sharp edges, basket in a choke — pick the material that survives that, or change the method." },
      { n: "05", title: "CHECK WLL", body: "After hitch and angle, the sling still has capacity. If it does not, change the sling or the hitch — do not hope." },
    ],
    prohibited: ["Selecting by colour or habit", "Knots in slings", "Synthetics on hot work they are not rated for"],
  }),
  swp("WHOOP-SWP-011", "slinging-loads", "SLINGING LOADS", "Connect the hitch as planned. Test it an inch off the ground.", {
    purpose: "Put the sling on the load so the tension goes where you calculated.",
    scope: "Making hitches on construction and industrial lifts WHOOP rigs.",
    competency: ["Rigger", "Can explain the hitch they are about to make"],
    hazards: ["Unstable piece", "Sharp edges", "Twisted slings", "Unbalanced COG", "People under"],
    controls: ["Block the load", "Protect edges", "Hardware straight", "Test lift", "Zone"],
    equipment: ["Selected slings and hardware", "Softeners", "Tag lines"],
    procedure: [
      { n: "01", title: "STABLE PIECE", body: "Block or shore so the load cannot roll onto the rigger." },
      { n: "02", title: "POINTS", body: "Designed lifting points. If none, the method is engineered or it is not a WHOOP hitch." },
      { n: "03", title: "APPLY THE HITCH", body: "No twists, no knots, no choke off a guess. Softeners on edges." },
      { n: "04", title: "HARDWARE", body: "Pins in. Latches working. Shackles used as designed." },
      { n: "05", title: "CLEAR AND TEST", body: "Hands off. Zone held. Inch off the ground. Re-rig if it tilts, slips or shocks." },
    ],
    prohibited: ["Wrapping a sling around a hook as a makeshift eye", "Riding the load to “balance it”", "Hands on a live sling"],
  }),
  swp("WHOOP-SWP-012", "shackles", "SHACKLES", "The right shackle, the right pin, the right way around.", {
    purpose: "Use shackles within WLL, with the pin that belongs to them, in the orientation they were made for.",
    scope: "Anchor, chain and other shackles used in WHOOP rigging.",
    competency: ["Can identify type and WLL", "Knows bow versus pin loading"],
    hazards: ["Bolt in place of a pin", "Side loading the pin", "Opened body", "Unmoused screw pin where required"],
    controls: ["Match pin to body", "Inspect", "Mouse screw pins where required", "Do not point-load a bow unless designed for it"],
    equipment: ["Identified shackles", "Correct pins"],
    procedure: [
      { n: "01", title: "IDENTIFY", body: "Type, WLL, pin that belongs to this body." },
      { n: "02", title: "INSPECT", body: "Wear, stretch, bent pin, opened jaw — out of service." },
      { n: "03", title: "ORIENT", body: "Load the bow and pin as designed. Do not side-load unless the manufacturer allows it." },
      { n: "04", title: "PIN", body: "Fully engaged. Screw pins moused where required. No truck-bolt specials." },
      { n: "05", title: "AFTER THE LIFT", body: "Inspect again. A pinched shackle is a failed shackle." },
    ],
    prohibited: ["Mixing pins between shackles", "Using a shackle as a hook by hanging it on an edge", "Welding on a shackle"],
  }),
  swp("WHOOP-SWP-013", "hooks", "HOOKS", "Latch works. Throat not opened. Tip not loaded.", {
    purpose: "Keep hooks in service only when they can hold the hitch they are asked to hold.",
    scope: "Crane hooks and rigging hooks WHOOP personnel use.",
    competency: ["Knows rejection for opening, wear and latch"],
    hazards: ["Missing latch", "Opened throat", "Tip loading", "Two slings fighting on one hook without a fitting"],
    controls: ["Inspect latch and throat", "Seat the sling in the saddle", "Out of service when the manufacturer says so"],
    equipment: ["The hook on the crane or in the hitch", "Latch"],
    procedure: [
      { n: "01", title: "INSPECT", body: "Latch function, wear in the saddle, throat opening, cracks, swivel." },
      { n: "02", title: "SEAT", body: "Sling or fitting in the saddle. Not on the tip. Not on the latch." },
      { n: "03", title: "LATCH", body: "If the latch is gone, the hook is out of service unless the hitch does not require it and the manufacturer allows it. Default is out of service." },
      { n: "04", title: "MULTI-LEG", body: "Use a shackle or master link. Do not stack legs so they walk off the hook." },
    ],
    prohibited: ["Wiring a latch shut", "Mousing as a substitute for a missing latch on a crane hook", "Shock loading a hook to “seat” it"],
  }),
  swp("WHOOP-SWP-014", "rigging-hardware", "RIGGING HARDWARE", "Rated, matched, inspected. No mystery steel.", {
    purpose: "Keep rings, links, turnbuckles, eyebolts, beam clamps and below-the-hook fittings inside their ratings.",
    scope: "Hardware other than slings, shackles and hooks used in WHOOP hitches.",
    competency: ["Can read the mark", "Knows when an eyebolt is for tension only"],
    hazards: ["Unmarked fittings", "Eyebolts loaded at an angle they were not made for", "Beam clamps on the wrong flange", "Welded shop specials"],
    controls: ["Identification", "Manufacturer orientation", "Inspect", "Engineer for homemade gear — which means homemade gear is out"],
    equipment: ["Marked hardware", "Manufacturer instructions"],
    procedure: [
      { n: "01", title: "IDENTIFY", body: "WLL and type. Unmarked — out of service." },
      { n: "02", title: "ORIENTATION", body: "Eyebolts, clamps and turnbuckles loaded the way they were made. Shoulder eyebolts are not a suggestion." },
      { n: "03", title: "INSPECT", body: "Threads, cracks, wear, deformation. Fail = tag and isolate." },
      { n: "04", title: "MATCH THE HITCH", body: "Capacity of the weakest piece in the hitch is the capacity of the hitch." },
    ],
    prohibited: ["Shop-welded lifting eyes without engineering", "Using construction rebar as a spreader", "C-clamps as lifting gear"],
  }),
  swp("WHOOP-SWP-015", "load-control", "LOAD CONTROL", "The load goes where the plan said. Not where it drifted.", {
    purpose: "Control rotation, swing and travel so people and plant are not in the path.",
    scope: "All WHOOP lifts once the load is on the hook.",
    competency: ["Operator, rigger and signalperson who briefed the path"],
    hazards: ["Spin", "Pendulum", "Contact", "People in the path", "Wind"],
    controls: ["Tag lines", "Exclusion zone", "Smooth motions", "No side pull"],
    equipment: ["Tag lines", "Zone marking", "Spotters if briefed"],
    procedure: [
      { n: "01", title: "PATH", body: "Pick, travel, set — walked and briefed." },
      { n: "02", title: "TAG LINES", body: "On before the load leaves the ground if rotation must be controlled." },
      { n: "03", title: "HOIST", body: "Smooth. No snatching. Boom and swing only with the load under control." },
      { n: "04", title: "ZONE", body: "Held for the whole time the load is in the air." },
      { n: "05", title: "IF IT GETS AWAY", body: "Stop the motion. Do not chase a spinning load with your body. Reset." },
    ],
    prohibited: ["Pushing a live load with a shoulder", "Side-pulling to drag a piece into place", "People using the load as a work platform"],
  }),
  swp("WHOOP-SWP-016", "tag-lines", "TAG LINES", "Lines control rotation. Bodies do not.", {
    purpose: "Use tag lines so the load does not spin into people, steel or the crane.",
    scope: "WHOOP lifts that require rotational control.",
    competency: ["Knows not to wrap a line on the body", "Can let go"],
    hazards: ["Wrap on wrist or waist", "Standing in the bight", "Pulled under the load", "Line snag"],
    controls: ["Correct length", "Hands that can release", "Position out of the fall zone and the bight"],
    equipment: ["Serviceable tag lines"],
    procedure: [
      { n: "01", title: "SELECT", body: "Length and condition for this load. Not a knot of leftover rope." },
      { n: "02", title: "ATTACH", body: "Points that will not slip off and will not cut the line." },
      { n: "03", title: "HOLD", body: "So you can let go. Never a turn around a wrist, belt or ankle." },
      { n: "04", title: "STAND", body: "Out of the fall zone, out of the pinch, out of the bight, out from under the boom." },
      { n: "05", title: "GUIDE", body: "If the load is winning, stop the crane and reset. You are not an anchor." },
    ],
    prohibited: ["Wrapping the line on your body", "Tying a tag line to a structure and pulling the crane over it", "Nylon on a sharp edge with no protection"],
  }),
  swp("WHOOP-SWP-017", "suspended-loads", "SUSPENDED LOADS", "If it is in the air, the zone is alive.", {
    purpose: "Keep people out from under a load and keep loads from hanging unattended.",
    scope: "Any time a load is off the ground on a WHOOP lift.",
    competency: ["Entire crew briefed on the zone"],
    hazards: ["People under", "Unattended hook", "Wind on a hanging piece", "Drift"],
    controls: ["Exclusion zone", "Tag lines", "Do not leave a hanging load", "Land when the plan says land"],
    equipment: ["Zone marking", "Tag lines"],
    procedure: [
      { n: "01", title: "ZONE BEFORE HOIST", body: "The fall zone is cleared and held before the load leaves the ground." },
      { n: "02", title: "WHILE IT IS UP", body: "Nobody walks under. Nobody uses the shadow as a shortcut." },
      { n: "03", title: "ATTENDED", body: "A named operator remains with the crane, or the load is landed. Convenience is not a reason to hang steel." },
      { n: "04", title: "WEATHER", body: "Wind rising: land or hold to the plan." },
      { n: "05", title: "LAND", body: "Prepared set. Stable before anyone goes in to disconnect." },
    ],
    prohibited: ["Standing under a suspended load", "Leaving a load hanging over a walkway", "Riding the load"],
  }),
  swp("WHOOP-SWP-018", "working-near-powerlines", "WORKING NEAR POWERLINES", "Assume they are live. Distance is a wall.", {
    purpose: "Keep boom, load, tag lines and people outside the minimum approach distance.",
    scope: "Any WHOOP lift where overhead or buried electrical lines exist, or might exist.",
    competency: ["Operator and supervisor who know the MAD for this voltage", "Spotter when required"],
    hazards: ["Contact", "Arc", "Step potential", "Unknown voltage", "Lines that “look dead”"],
    controls: ["Identify", "MAD as a hard wall", "Spotter", "Utility when the lift cannot keep clearance", "Brief the jump procedure"],
    equipment: ["Spotter", "Range limiting if fitted and used", "Utility documentation if the line is to be covered or de-energized"],
    procedure: [
      { n: "01", title: "FIND THE LINES", body: "Look up. Ask the site. Do not trust a single drawing." },
      { n: "02", title: "VOLTAGE AND MAD", body: "Treat unknown as the worst case the site will allow you to plan to. If you cannot keep MAD, it is not a crane job until the utility says it is." },
      { n: "03", title: "SPOTTER", body: "When the boom or load can encroach, a dedicated spotter whose only job is the line." },
      { n: "04", title: "LIMIT THE CRANE", body: "Use the plan, the chart and any limiting device. Do not “be careful” as the control." },
      { n: "05", title: "CONTACT", body: "Stay on the crane unless fire or shock forces you off. Nobody approaches. Call the utility. If you must get off: jump clear, feet together, shuffle away. This is briefed before the lift, not during the contact." },
    ],
    prohibited: ["Guessing voltage", "Using a two-by-four to “hold the line”", "Tag lines that can blow into a line"],
    emergency: "Do not touch the crane or the load. Keep people back. Call the utility and emergency services. Operator stays on unless fire or shock. WHOOP notified immediately.",
  }),
  swp("WHOOP-SWP-019", "critical-lifts", "CRITICAL LIFTS", "Slower brief. Named supervision. Written plan. Ego is not a control.", {
    purpose: "Run lifts that can hurt a lot of people, or a lot of plant, as critical — not as a louder version of a routine pick.",
    scope: "Loads approaching chart capacity, tandem / multiple crane, lifts over operating plant or public space, non-routine paths, shifting COG, and any lift the site or this program calls critical.",
    competency: ["Named supervisor", "Crew that can repeat the abort", "Engineer when required"],
    hazards: ["Overconfidence", "Skipped hold points", "Unclear roles", "Tandem mismatch"],
    controls: ["Written critical lift plan", "Pre-lift meeting", "Hold points", "Named people"],
    equipment: ["WHOOP-FRM-007", "Radios", "The crane and rigging in the plan"],
    procedure: [
      { n: "01", title: "DECLARE IT", body: "Why it is critical — said in the brief, written on the plan." },
      { n: "02", title: "PLAN", body: "Sequence, weights, radii, rigging, holds, abort, rescue. At the lift." },
      { n: "03", title: "PEOPLE", body: "Operator, rigger, signal, supervisor, engineer if required. Named." },
      { n: "04", title: "MEETING", body: "Everyone repeats the plan, the signals, who stops it. If they cannot, the brief failed." },
      { n: "05", title: "EXECUTE HOLDS", body: "Do not skip a hold because the crane is waiting." },
      { n: "06", title: "ABORT", body: "Any unmet condition: stop. Rewrite. Do not “adapt on the fly.”" },
    ],
    prohibited: ["Calling it critical and then running it like a grocery pick", "Tandem lifts without a plan and a single lead"],
    documentation: ["WHOOP-FRM-007", "WHOOP-FRM-009", "SJP if required"],
  }),
  swp("WHOOP-SWP-020", "lift-planning", "LIFT PLANNING", "Weight, COG, chart, path, people, abort — before the hook.", {
    purpose: "Build a plan that a crew can actually follow.",
    scope: "Non-routine lifts, tight sites, and any lift the supervisor or operator asks to be planned. Routine picks still need an FLHA.",
    competency: ["Supervisor or designated planner", "Operator who will refuse a plan they cannot run"],
    hazards: ["Unknown weight", "Chart fiction", "Path not walked", "Roles implied"],
    controls: ["Facts before ink", "Walk the path", "Named crew", "Hard limits"],
    equipment: ["WHOOP-FRM-006", "Drawings and shipping data", "Chart"],
    procedure: [
      { n: "01", title: "COLLECT FACTS", body: "Load data, drawings, crane, ground, energy, other work." },
      { n: "02", title: "CHART IT", body: "Configuration, radius, deductions, rigging weight. If it does not fit, change the method — not the numbers." },
      { n: "03", title: "RIGGING", body: "Hitch, WLL, angles, hardware. Attach a rigging plan when the hitch is not obvious." },
      { n: "04", title: "PATH AND ZONE", body: "Walk it. Mark it. Include the swing." },
      { n: "05", title: "PEOPLE AND ABORT", body: "Names. Radios. Wind, visibility, radio loss. Numbers, not vibes." },
      { n: "06", title: "BRIEF AND KEEP IT", body: "The plan stays at the lift. Drift = stop and rewrite." },
    ],
    prohibited: ["Planning in the cab after the load is hooked", "Using last week’s plan because the steel “looks the same”"],
    documentation: ["WHOOP-FRM-006", "FLHA", "Rigging plan if used"],
  }),
  swp("WHOOP-SWP-021", "outrigger-setup", "OUTRIGGER SETUP", "Fully extended unless the chart for short-rig is in the cab and in use.", {
    purpose: "Put the pads where the manufacturer said the reactions go.",
    scope: "Mobile cranes and boom trucks with outriggers or stabilizers.",
    competency: ["Operator for this crane", "Understands this chart’s outrigger positions"],
    hazards: ["Short-rigging without a chart", "Undersized mats", "Soft ground", "Punch-through", "People in the jack line"],
    controls: ["Chart position", "Mats", "Level", "Keep people clear while jacking"],
    equipment: ["Outriggers", "Mats / cribbing", "Level"],
    procedure: [
      { n: "01", title: "CHART POSITION", body: "Which outrigger position this lift is planned on. If short-rig, that chart is the chart — not a memory." },
      { n: "02", title: "CLEAR", body: "People out of the jack line and from under the machine while it is going up." },
      { n: "03", title: "MATS", body: "Sized for the reaction. On competent ground. Not on a sidewalk lid you have not proven." },
      { n: "04", title: "SET AND LEVEL", body: "Floats or tires as the manufacturer requires. Level within limit. Recheck after the first load if the ground can give." },
      { n: "05", title: "CONFIRM", body: "Pins, beams, jacks — in the position you told the chart." },
    ],
    prohibited: ["Partial beams “just for this pick” without that configuration on the chart", "Cribbing that is a pile of broken dunnage", "Standing beside a jack under pressure to “watch it”"],
  }),
  swp("WHOOP-SWP-022", "ground-conditions", "GROUND CONDITIONS", "If the ground cannot hold the crane, it is not a crane job yet.", {
    purpose: "Treat supporting surface as a lifting control, not as dirt.",
    scope: "Setup of mobile cranes and any blocking under outriggers, crawlers or loads being set.",
    competency: ["Operator and supervisor who will stop on bad ground", "Engineer when the site or the load requires it"],
    hazards: ["Backfill", "Vaults", "Thaw", "Slope", "Buried services", "Mats too small"],
    controls: ["Walk and ask", "Locate services", "Mats", "Engineer for doubtful ground", "Stop"],
    equipment: ["Mats", "Site drawings if they exist", "Utility locates"],
    procedure: [
      { n: "01", title: "LOOK AND ASK", body: "What is under this pad. Cellars, tanks, trenches, recent fill. The site should know. If they do not, stop." },
      { n: "02", title: "SERVICES", body: "Locates for underground. Do not invent a pad over a main." },
      { n: "03", title: "CAPACITY", body: "Manufacturer reactions versus what this surface can take. Mats spread load. They do not create bearing that is not there." },
      { n: "04", title: "SLOPE AND WATER", body: "Level the crane as required. Water, ice and thaw change yesterday’s pad." },
      { n: "05", title: "WATCH IT", body: "First load is a test of the ground as well as the hitch. Settlement = down and reassess." },
    ],
    prohibited: ["Setting on plywood over mud and calling it engineered", "Ignoring a locate because “we’ve always set here”"],
  }),
  swp("WHOOP-SWP-023", "weather-and-wind", "WEATHER AND WIND", "The lower number wins. A breeze is not a number.", {
    purpose: "Stop the lift when wind, lightning, ice or visibility take the plan away.",
    scope: "All WHOOP crane and rigging operations outdoors, and indoors where wind through a bay matters.",
    competency: ["Operator who will believe the anemometer over the superintendent"],
    hazards: ["Side load from wind", "Load sail", "Lightning", "Ice on the crane and on the load", "Loss of visibility"],
    controls: ["Manufacturer limit", "Lift plan limit", "Anemometer or site reading", "Lightning rule", "Land when told"],
    equipment: ["A way to know the wind", "Manufacturer weather limits"],
    procedure: [
      { n: "01", title: "LIMITS IN THE BRIEF", body: "Manufacturer and plan. The lower number is the number." },
      { n: "02", title: "MEASURE", body: "Use a real reading, not a vibe. Account for load sail — a panel is not a block." },
      { n: "03", title: "LIGHTNING", body: "Boom down. People off the machine and off the load. Resume only when the plan says so." },
      { n: "04", title: "ICE AND SNOW", body: "Clear the crane as the manufacturer requires. A load with a snow cap has a different weight and a different sail." },
      { n: "05", title: "STOP", body: "When the number is hit, land or shut down. Argument is not a control." },
    ],
    prohibited: ["“We’ll sneak this one in” over the wind limit", "Raising a boom into a thunderstorm to finish the day"],
  }),
  swp("WHOOP-SWP-024", "crane-emergency-procedures", "CRANE EMERGENCY PROCEDURES", "People first. Then the machine. Then the story.", {
    purpose: "Give the crew one sequence when the crane, the load or a person is in trouble.",
    scope: "Incidents during WHOOP crane operations: overload alarms, function failure, contact, fire, medical, overturn developing.",
    competency: ["Entire crew briefed on emergency shutdown for this machine"],
    hazards: ["Second incident", "People approaching a live crane", "Uncontrolled load", "Fire in the engine or cab"],
    controls: ["Stop", "Safe condition if possible", "Keep people back", "Call for help", "Notify WHOOP"],
    equipment: ["This crane’s emergency stops", "Extinguisher in the cab", "Site emergency number"],
    procedure: [
      { n: "01", title: "STOP", body: "Stop motions that make it worse. Emergency stop if that is the control." },
      { n: "02", title: "PEOPLE", body: "Get people out of the zone. First aid. Do not become the second event." },
      { n: "03", title: "LOAD", body: "Land or hold only if it can be done without creating another failure. If it cannot, protect people and wait for a plan." },
      { n: "04", title: "MACHINE", body: "Fire: extinguisher if you are trained and it is small; otherwise get off and keep people back. Overturn developing: do not jump toward the fall." },
      { n: "05", title: "CALL AND HOLD", body: "Site emergency method. Utility if lines. WHOOP. Scene held for investigation." },
    ],
    prohibited: ["Restarting to “see if it does it again”", "Crowd around a crane in contact with a line", "Moving a seriously injured person except from immediate danger"],
    documentation: ["Incident report WHOOP-FRM-010", "Machine log"],
  }),
  swp("WHOOP-SWP-025", "removal-of-damaged-rigging", "REMOVAL OF DAMAGED RIGGING FROM SERVICE", "Tag it. Isolate it. Tell someone. No one more lift.", {
    purpose: "Make sure failed gear cannot be picked up by the next rigger.",
    scope: "Any sling or hardware that fails inspection or is damaged in use on a WHOOP dispatch.",
    competency: ["Anyone on the crew can stop gear", "Rigger completes the tag and report"],
    hazards: ["Failed gear left on the pile", "Unmarked damage", "Someone “borrowing” a cut sling"],
    controls: ["Immediate removal", "Physical isolation", "Tag", "Report WHOOP-RPT-004"],
    equipment: ["Out-of-service tags", "A place that is not the working pile"],
    procedure: [
      { n: "01", title: "STOP USING IT", body: "The hitch comes off. The lift waits or is re-rigged with serviceable gear." },
      { n: "02", title: "TAG", body: "What failed, when, who. Tied to the item." },
      { n: "03", title: "ISOLATE", body: "Off the working pile. In a reject bin, a locked bag, or the truck’s quarantine — not beside the good slings." },
      { n: "04", title: "REPORT", body: "WHOOP-RPT-004 the same shift. Site if it is their gear." },
      { n: "05", title: "DO NOT REPAIR IN THE FIELD", body: "No wrapping tape as a WLL. No welding a hook. Destroy or return through WHOOP or the owner." },
    ],
    prohibited: ["Leaving a cut sling “so nobody trips on it” on the pile", "Cutting the tag off because the sling is “still good in the middle”"],
    documentation: ["WHOOP-FRM-003", "WHOOP-RPT-004"],
  }),
  swp("WHOOP-SWP-026", "lockout", "LOCKOUT / ISOLATION", "If you are not operating it, the energy is isolated. Part 10.", {
    purpose: "Keep a person off stored energy — hoist, slew, luff, travel, hydraulics, electrical — when the work is service, inspection beyond pre-use, rescue, or anything that puts a body in the machine.",
    scope: "WHOOP personnel on a crane they are not operating: maintenance they are assigned, climbing past the cab for inspection, rescue, or working on WHOOP-controlled tools and vehicles. Not a substitute for the owner’s lockout procedure on that crane. Not tower jumping — see WHOOP-SWP-027.",
    competency: ["Understands this machine’s isolation. Follows the owner’s lockout where it exists. Does not invent a padlock on a live hoist."],
    hazards: ["Unexpected hoist or slew", "Hydraulic dump", "Electrical contact", "Someone starting the crane", "Stored energy in a luffing ram"],
    controls: ["Identify energy", "Isolate", "Lock and tag", "Verify zero energy", "One lock per person"],
    equipment: ["Personal lock", "Tag", "The owner’s lockout devices for this crane"],
    procedure: [
      { n: "01", title: "NAME THE WORK", body: "What is being done, on which machine, which energy. If you cannot name it, you are not isolating it." },
      { n: "02", title: "OWNER’S PROCEDURE", body: "Use the lockout written for this crane when it exists. WHOOP does not override a stricter owner procedure." },
      { n: "03", title: "ISOLATE AND LOCK", body: "Controls off. Energy isolated. Personal lock and tag. One person, one lock. Do not lend a key." },
      { n: "04", title: "VERIFY", body: "Try to start. Confirm the hoist, slew and luff will not move. Residual hydraulic or raised jib — released or blocked as the manufacturer says." },
      { n: "05", title: "WORK, THEN REMOVE YOUR LOCK", body: "Do the work. Remove only your lock. If the job runs past a shift, the handover of locks is a procedure — not a text message." },
    ],
    prohibited: ["Reaching into a machine that can still hoist", "Sharing a lock because ‘we’re both on it’", "Bypassing a limit to ‘just inch it’ during service"],
    documentation: ["Owner lockout for this serial", "WHOOP-FRM-002 / 027 if the machine was down for a defect"],
    emergency: "If energy appears during the work: get clear. Re-isolate. Do not finish the job on a live machine.",
  }),
  swp("WHOOP-SWP-027", "tower-erection-climbing", "TOWER ERECTION, CLIMBING AND DISMANTLING", "Not a routine operator dispatch. Qualified supervisor. Notice of Project. 14.73.2.", {
    purpose: "Stop WHOOP from treating jumping a tower like running a shift. If this is the work, it is planned as this work.",
    scope: "Tower-crane erection, climbing (increasing height), repositioning and dismantling. Not climbing the ladder to the cab to operate. Not a how-to for jumping a crane.",
    competency: ["Work under a qualified supervisor as 14.73.2 and 14.73.3 require. WHOOP does not send an operator to jump a crane because they have a tower ticket."],
    hazards: ["Unplanned jump", "Missing NOP", "No qualified supervisor", "People under a climbing frame", "Wind during a climb", "Lockout not done"],
    controls: ["This is a planned operation or it is not WHOOP work", "Notice of Project at least two weeks before, as 14.73.3 requires", "Qualified supervisor", "Manufacturer sequence", "Exclusion zone", "Lockout"],
    equipment: ["This crane’s erection / climbing manual", "The climbing frame for this serial", "WHOOP-SWP-026"],
    procedure: [
      { n: "01", title: "CONFIRM THE DISPATCH", body: "The work is erection, climbing or dismantling — said in writing. A tower operator call is not this call." },
      { n: "02", title: "SUPERVISOR AND NOP", body: "Qualified supervisor named. Notice of Project to WorkSafeBC on the timeline 14.73.3 names. If either is missing, the work does not start." },
      { n: "03", title: "MANUAL AND CONFIGURATION", body: "This serial, this tower system, this climbing frame, this tie-in. The manufacturer’s sequence is the sequence." },
      { n: "04", title: "ZONE AND WEATHER", body: "Exclusion under the work. Wind and weather as the manufacturer and the plan. People off the ground under the frame." },
      { n: "05", title: "ISOLATE WHEN REQUIRED", body: "Lockout / isolation when anyone is in the machine for this work. WHOOP-SWP-026." },
      { n: "06", title: "STOP", body: "Any step that is not in the manual, any missing pin, any unplanned person in the zone — stop. Rewrite. Do not improvise a jump." },
    ],
    prohibited: ["An operator jumping a crane as a favour", "Skipping the NOP because the pour is tomorrow", "Using a different manufacturer’s climbing notes"],
    documentation: ["NOP-TC", "Site binder checklist", "Qualified supervisor named", "Manufacturer erection / climbing procedure for this serial"],
  }),
];

export function getSwp(slug: string) {
  return SWPS.find((item) => item.slug === slug);
}
